#!/bin/bash
# spring boot base configuration

echo ":::configuring..." 

# setup base 
APP="app"
PKG="com/cagnosolutions/cei/springboot"

# setup github info
GITUSER="scottcagno"
GITPASS="d10No335"
RESOURCE="spring-boot-setup"

# get main resources
echo ":::getting main resource files..." 
git clone https://$GITUSER:$GITPASS@github.com/$GITUSER/$RESOURCE.git

# init build file and properties
echo ":::initializing build file, and *.properties files..." 
cp $RESOURCE/build.gradle .

# init main entry point
echo ":::initializing main entry sources..." 
mkdir -p src/main/java/$PKG/$APP
cp $RESOURCE/App.java src/main/java/$PKG/$APP

# init base config sources
echo ":::initializing base config sources..." 
mkdir src/main/java/$PKG/$APP/config
cp $RESOURCE/*Config.java src/main/java/$PKG/$APP/config

# init base controller sources
echo ":::initializing base controller sources..." 
mkdir src/main/java/$PKG/$APP/controller
cp $RESOURCE/*Controller.java src/main/java/$PKG/$APP/controller

# init base service sources
echo ":::initializing base service sources..." 
mkdir src/main/java/$PKG/$APP/service
cp $RESOURCE/*Service.java src/main/java/$PKG/$APP/service

# init base data access sources
echo ":::initializing base data access sources..." 
mkdir src/main/java/$PKG/$APP/data
cp $RESOURCE/*Repository.java src/main/java/$PKG/$APP/data

# init base domain model sources
echo ":::initializing base domain model sources..." 
mkdir src/main/java/$PKG/$APP/domain
cp $RESOURCE/User.java src/main/java/$PKG/$APP/domain

# initialize main resource structure
echo ":::initializing base resources folder structure..."
mkdir -p src/main/resources
cp $RESOURCE/*.properties src/main/resources
cp -r $RESOURCE/static src/main/resources

# initialize main templating structure
echo ":::initializing base templates folder structure"
mkdir src/main/resources/templates
cp -r $RESOURCE/templates src/main/resources

# adding libs to eclipse classpath
gradle eclipse

# cleanup
echo ":::cleaning up..."
rm -rf $RESOURCE

PKG=`echo $PKG | sed -e "s/\//./g"`
find . -name "*.java" -print0 | xargs -0 sed -i "" -e "s/\$\P\A\C\K\A\G\E/$PKG\.$APP/g"

# done
echo ":::done!"

# running
echo ":::running..."
clear; gradle clean build; clear; java -jar build/libs/springboot.jar
canberra-gtk-play -l 3 --file=/usr/share/sounds/ubuntu/stereo/bell.ogg
